---
# group_vars/all.yml

ansible_python_interpreter: "/usr/bin/env python3"
image: ami-0c55b159cbfafe1f0
region: us-east-2
keypair: "name of the keypair on aws that you want to use"
vpcid: "id of the vpc. this will be used for subnet creation"
localsubnet: x.x.x.x/x
taskname: devopstask
loadb: "{{taskname}}-lb"
auto_sc:  "{{taskname}}_asg"
lc: "{{taskname}}_lc"
websrv_subnet: "{{taskname}}_sb"
security_groups: default
instance_type: t2.micro
volumes:
  - device_name: /dev/sda1
    device_type: gp2
    volume_size: 20
    delete_on_termination: true






