---
# group_vars/all.yml

ansible_python_interpreter: "/usr/bin/env python3"
image: ami-0c55b159cbfafe1f0
region: us-east-2
keypair: task
security_groups: default
instance_type: t2.micro
volumes:
  - device_name: /dev/sda1
    device_type: gp2
    volume_size: 20
    delete_on_termination: true

