
- name: Launch new instance
  ec2:
    aws_access_key: '{{ ami_access }}'
    aws_secret_key: '{{ ami_secret }}'
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    group: "{{ security_groups }}"
    image: "{{ image }}"
    vpc_subnet_id: subnet-07a421fc60ac0c557
    assign_public_ip: yes
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: devopstask
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

 #- name: Add new instances to host group
 # add_host:
 # name: "{{ item.public_dns_name }}"
 #  groups: "{{ name }}"
 #  ec2_id: "{{ item.id }}"
 # with_items: ec2.instances


- name: Add the newly created host so that we can further contact it
  add_host:
    name: "{{ item.public_ip }}"
    groups: ami_img
  with_items: "{{ ec2.instances }}"

- name: store the ec2 id
  add_host:
    name: idholder
    instance_id: "{{item.id}}"
  with_items: "{{ ec2.instances }}"

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: "{{ec2.instances}}"
